-- Public exam keys are shared across accounts and consume one global quota
-- for every newly-created exam session. join_exam already locks the key row
-- with FOR UPDATE, so used_attempts remains race-safe under concurrent joins.

alter table public.key_batches
  add column if not exists is_public boolean not null default false;
alter table public.exam_keys
  add column if not exists is_public boolean not null default false;
alter table public.exam_keys
  drop constraint if exists exam_keys_public_unassigned;
alter table public.exam_keys
  add constraint exam_keys_public_unassigned
  check (not is_public or assigned_to is null);
create index if not exists exam_keys_public_status_idx
  on public.exam_keys(status, expires_at)
  where is_public;
comment on column public.exam_keys.is_public is
  'When true, the key can be used by multiple accounts and total_attempts is a shared global quota.';
comment on column public.key_batches.is_public is
  'Whether keys generated by this batch are shared public keys.';
-- Existing join/activation functions assign a key to the current student.
-- Keep public keys ownerless so the next account can pass the same ownership
-- check. The row-level quota update remains unchanged and atomic.
create or replace function private.fn_exam_keys_guard_owner()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.is_public then
    new.assigned_to := null;
    return new;
  end if;

  if old.assigned_to is distinct from new.assigned_to
    and old.assigned_to is not null
    and new.assigned_to is not null
    and old.assigned_to <> new.assigned_to
  then
    raise exception 'KEY_ALREADY_ASSIGNED'
      using errcode = 'P0001',
            hint = 'KEY_ALREADY_ASSIGNED';
  end if;

  return new;
end;
$$;
comment on function private.fn_exam_keys_guard_owner() is
  'Keeps public keys ownerless while preventing private keys from moving directly between students.';
-- A student's current_key_id may reference a shared public key even though
-- that key intentionally has no assigned_to owner.
create or replace function private.ensure_student_current_key_matches()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  key_owner uuid;
  key_is_public boolean;
begin
  if new.current_key_id is null then
    return new;
  end if;

  select k.assigned_to, k.is_public
    into key_owner, key_is_public
  from public.exam_keys k
  where k.id = new.current_key_id;

  if not found then
    raise exception 'Current key does not exist';
  end if;

  if not key_is_public and key_owner is distinct from new.id then
    raise exception 'Current key must be assigned to the same student';
  end if;

  return new;
end;
$$;
create or replace view public.admin_exam_key_overview
with (security_invoker = true)
as
select
  ek.id,
  ek.code,
  ek.exam_room_id,
  coalesce(er.name, 'Dùng cho mọi phòng thi') as exam_room_name,
  er.subject_code,
  coalesce(s.name, 'Tất cả môn') as subject_name,
  ek.batch_id,
  ek.assigned_to,
  st.full_name as student_name,
  ek.total_attempts,
  ek.used_attempts,
  greatest(ek.total_attempts - ek.used_attempts, 0) as remaining_attempts,
  ek.status,
  ek.expires_at,
  ek.created_at,
  kb.quantity as batch_quantity,
  kb.expires_at as batch_expires_at,
  ek.is_public
from public.exam_keys ek
left join public.exam_rooms er on er.id = ek.exam_room_id
left join public.subjects s on s.code = er.subject_code
left join public.students st on st.id = ek.assigned_to
left join public.key_batches kb on kb.id = ek.batch_id
where private.is_staff();
create or replace view public.student_key_summary
with (security_invoker = true)
as
select
  st.id as student_id,
  p.email as gmail,
  st.full_name,
  st.school_name,
  st.province_name,
  st.district_name,
  st.phone,
  st.current_key_id,
  k.code as current_key_code,
  k.status as current_key_status,
  k.exam_room_id,
  er.code as exam_room_code,
  er.name as exam_room_name,
  er.subject_code,
  k.total_attempts,
  k.used_attempts,
  greatest(k.total_attempts - k.used_attempts, 0) as remaining_attempts,
  (k.used_attempts > 0) as current_key_has_been_used,
  k.expires_at as current_key_expires_at,
  coalesce(key_stats.assigned_key_count, 0) as assigned_key_count,
  coalesce(key_stats.used_key_count, 0) as used_key_count,
  coalesce(key_stats.exhausted_key_count, 0) as exhausted_key_count
from public.students st
left join public.profiles p on st.id = p.id
left join lateral (
  select ek.*
  from public.exam_keys ek
  where (
      ek.assigned_to = st.id
      or (ek.is_public and ek.id = st.current_key_id)
    )
    and (st.current_key_id is null or ek.id = st.current_key_id)
  order by coalesce(ek.id = st.current_key_id, false) desc, ek.created_at desc
  limit 1
) k on true
left join public.exam_rooms er on er.id = k.exam_room_id
left join lateral (
  select
    count(*)::int as assigned_key_count,
    count(*) filter (where ek.used_attempts > 0)::int as used_key_count,
    count(*) filter (where ek.status = 'exhausted')::int as exhausted_key_count
  from public.exam_keys ek
  where ek.assigned_to = st.id
) key_stats on true;
-- This room-scoped overload is used by the admin UI. The older global-key
-- overload remains available for backward compatibility.
create or replace function public.generate_exam_keys(
  p_exam_room_id uuid,
  p_quantity int,
  p_expires_at timestamptz,
  p_note text,
  p_total_attempts int,
  p_is_public boolean
)
returns table (
  id uuid,
  code text,
  exam_room_id uuid,
  batch_id uuid,
  subject_code text,
  exam_room_name text,
  is_public boolean,
  total_attempts int,
  used_attempts int,
  status public.exam_key_status,
  expires_at timestamptz,
  created_at timestamptz
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_room record;
  v_batch_id uuid;
  v_code text;
  v_key public.exam_keys%rowtype;
  v_counter int;
  v_retry int;
begin
  if (select auth.uid()) is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;

  if not private.is_staff() then
    raise exception 'Only staff can generate exam keys' using errcode = '42501';
  end if;

  if p_exam_room_id is null then
    raise exception 'Exam room is required';
  end if;

  if p_quantity is null or p_quantity < 1 or p_quantity > 500 then
    raise exception 'Quantity must be between 1 and 500';
  end if;

  if p_total_attempts is null or p_total_attempts < 1 or p_total_attempts > 100000 then
    raise exception 'Total attempts must be between 1 and 100000';
  end if;

  if p_is_public is null then
    raise exception 'Key visibility is required';
  end if;

  if p_expires_at is not null and p_expires_at <= now() then
    raise exception 'Key expiry must be in the future';
  end if;

  select
    er.id,
    er.name,
    er.subject_code,
    er.status,
    b.exam_year
  into v_room
  from public.exam_rooms er
  join public.exam_blueprints b on b.id = er.blueprint_id
  where er.id = p_exam_room_id;

  if v_room.id is null then
    raise exception 'Exam room not found';
  end if;

  if v_room.status <> 'published' then
    raise exception 'Keys can only be generated for published exam rooms';
  end if;

  insert into public.key_batches as kb (
    exam_room_id,
    quantity,
    note,
    created_by,
    expires_at,
    total_attempts,
    is_public
  )
  values (
    p_exam_room_id,
    p_quantity,
    nullif(trim(p_note), ''),
    (select auth.uid()),
    p_expires_at,
    p_total_attempts,
    p_is_public
  )
  returning kb.id into v_batch_id;

  for v_counter in 1..p_quantity loop
    v_retry := 0;

    loop
      v_retry := v_retry + 1;
      v_code := upper(
        case when p_is_public then 'PUB-' else '' end
        || v_room.subject_code
        || '-'
        || v_room.exam_year::text
        || '-'
        || substr(replace(extensions.gen_random_uuid()::text, '-', ''), 1, 10)
      );

      begin
        insert into public.exam_keys (
          code,
          exam_room_id,
          batch_id,
          is_public,
          total_attempts,
          expires_at,
          status
        )
        values (
          v_code,
          p_exam_room_id,
          v_batch_id,
          p_is_public,
          p_total_attempts,
          p_expires_at,
          'unused'
        )
        returning * into v_key;

        id := v_key.id;
        code := v_key.code;
        exam_room_id := v_key.exam_room_id;
        batch_id := v_key.batch_id;
        subject_code := v_room.subject_code;
        exam_room_name := v_room.name;
        is_public := v_key.is_public;
        total_attempts := v_key.total_attempts;
        used_attempts := v_key.used_attempts;
        status := v_key.status;
        expires_at := v_key.expires_at;
        created_at := v_key.created_at;

        return next;
        exit;
      exception
        when unique_violation then
          if v_retry >= 5 then
            raise;
          end if;
      end;
    end loop;
  end loop;
end;
$$;
revoke all on function public.generate_exam_keys(uuid, int, timestamptz, text, int, boolean)
  from public, anon;
grant execute on function public.generate_exam_keys(uuid, int, timestamptz, text, int, boolean)
  to authenticated;
grant select on public.admin_exam_key_overview to authenticated;
grant select on public.student_key_summary to authenticated;
notify pgrst, 'reload schema';
