-- Bank checkout and purchased global-key entitlement.
-- Forward-only: tolerates the optional foundation tables already existing while
-- creating the same contract when this migration is applied to live directly.

create table if not exists public.key_products (
  id uuid primary key default extensions.gen_random_uuid(),
  code text not null unique,
  name text not null,
  product_kind text not null check (product_kind in ('exam', 'practice', 'bundle')),
  attempt_count integer not null check (attempt_count > 0),
  price_amount integer not null check (price_amount >= 0),
  currency text not null default 'VND' check (currency ~ '^[A-Z]{3}$'),
  valid_days integer check (valid_days is null or valid_days > 0),
  is_active boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

alter table public.key_products
  add column if not exists valid_days integer;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'key_products_valid_days_positive'
      and conrelid = 'public.key_products'::regclass
  ) then
    alter table public.key_products
      add constraint key_products_valid_days_positive
      check (valid_days is null or valid_days > 0);
  end if;
end
$$;

create table if not exists public.purchase_orders (
  id uuid primary key default extensions.gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete restrict,
  product_id uuid references public.key_products(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'fulfilled', 'failed', 'cancelled', 'refunded')),
  amount integer not null check (amount >= 0),
  currency text not null default 'VND' check (currency ~ '^[A-Z]{3}$'),
  product_snapshot jsonb not null,
  provider text,
  provider_order_ref text,
  idempotency_key text not null unique,
  payment_code text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  fulfilled_at timestamptz,
  failed_at timestamptz,
  failure_code text
);

alter table public.purchase_orders
  add column if not exists payment_code text,
  add column if not exists expires_at timestamptz;

update public.purchase_orders
set payment_code = 'LEGACY' || upper(replace(id::text, '-', ''))
where payment_code is null;

alter table public.purchase_orders
  alter column payment_code set not null;

create unique index if not exists purchase_orders_payment_code_unique
  on public.purchase_orders (payment_code);
create unique index if not exists purchase_orders_provider_ref_unique
  on public.purchase_orders (provider, provider_order_ref)
  where provider is not null and provider_order_ref is not null;
create index if not exists purchase_orders_student_created_idx
  on public.purchase_orders (student_id, created_at desc);
create index if not exists purchase_orders_status_created_idx
  on public.purchase_orders (status, created_at desc);

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  order_id uuid references public.purchase_orders(id) on delete set null,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  payload_sha256 text not null check (payload_sha256 ~ '^[0-9a-f]{64}$'),
  payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_error text,
  unique (provider, provider_event_id)
);

create index if not exists payment_events_order_received_idx
  on public.payment_events (order_id, received_at desc);
create index if not exists payment_events_error_received_idx
  on public.payment_events (processing_error, received_at desc)
  where processing_error is not null;

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  request_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_entity_created_idx
  on public.admin_audit_log (entity_type, entity_id, created_at desc);

alter table public.admin_audit_log enable row level security;
drop policy if exists admin_audit_log_admin_read on public.admin_audit_log;
create policy admin_audit_log_admin_read
on public.admin_audit_log for select to authenticated
using (private.is_admin());
revoke all on public.admin_audit_log from anon, authenticated;
grant select on public.admin_audit_log to authenticated;

alter table public.exam_keys
  alter column exam_room_id drop not null,
  add column if not exists source_order_id uuid;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'exam_keys_source_order_id_fkey'
      and conrelid = 'public.exam_keys'::regclass
  ) then
    alter table public.exam_keys
      add constraint exam_keys_source_order_id_fkey
      foreign key (source_order_id)
      references public.purchase_orders(id)
      on delete set null;
  end if;
end
$$;

create unique index if not exists exam_keys_source_order_unique
  on public.exam_keys (source_order_id)
  where source_order_id is not null;

-- The event row is intentionally append-only. The service role reaches it only
-- through the bank processor in the follow-up migration; dashboard users can read errors but cannot
-- mutate provider evidence.
create or replace function private.prevent_payment_event_mutation()
returns trigger
language plpgsql
security definer
set search_path to ''
as $$
begin
  raise exception 'PAYMENT_EVENT_IMMUTABLE';
end;
$$;

revoke all on function private.prevent_payment_event_mutation() from public, anon, authenticated;

drop trigger if exists payment_events_immutable on public.payment_events;
create trigger payment_events_immutable
before update or delete on public.payment_events
for each row execute function private.prevent_payment_event_mutation();

alter table public.key_products enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.payment_events enable row level security;

drop policy if exists key_products_authenticated_read on public.key_products;
create policy key_products_authenticated_read
on public.key_products for select to authenticated
using ((is_active and archived_at is null) or private.is_admin());

drop policy if exists key_products_admin_write on public.key_products;
create policy key_products_admin_write
on public.key_products for all to authenticated
using (private.is_admin())
with check (private.is_admin());

drop policy if exists purchase_orders_owner_read on public.purchase_orders;
create policy purchase_orders_owner_read
on public.purchase_orders for select to authenticated
using (student_id = (select auth.uid()) or private.is_admin());

drop policy if exists purchase_orders_authenticated_write on public.purchase_orders;
drop policy if exists purchase_orders_admin_write on public.purchase_orders;
create policy purchase_orders_admin_write
on public.purchase_orders for all to authenticated
using (private.is_admin())
with check (private.is_admin());

drop policy if exists payment_events_admin_read on public.payment_events;
create policy payment_events_admin_read
on public.payment_events for select to authenticated
using (private.is_admin());

revoke all on public.key_products, public.purchase_orders, public.payment_events
  from anon, authenticated;
grant select on public.key_products to authenticated;
grant insert, update, delete on public.key_products to authenticated;
grant select on public.purchase_orders, public.payment_events to authenticated;

drop trigger if exists key_products_updated_at on public.key_products;
create trigger key_products_updated_at
before update on public.key_products
for each row execute function private.touch_updated_at();

drop trigger if exists purchase_orders_updated_at on public.purchase_orders;
create trigger purchase_orders_updated_at
before update on public.purchase_orders
for each row execute function private.touch_updated_at();

-- Ensure the two catalog/order tables participate in the existing admin audit
-- stream when the foundation migration has already created that trigger.
do $$
begin
  if to_regprocedure('private.audit_admin_mutation()') is not null then
    execute 'drop trigger if exists audit_admin_mutation on public.key_products';
    execute 'create trigger audit_admin_mutation after insert or update or delete on public.key_products for each row execute function private.audit_admin_mutation()';
    execute 'drop trigger if exists audit_admin_mutation on public.purchase_orders';
    execute 'create trigger audit_admin_mutation after insert or update or delete on public.purchase_orders for each row execute function private.audit_admin_mutation()';
  end if;
end
$$;

create or replace function private.fulfill_purchase_order(
  p_order_id uuid,
  p_provider_reference text default null
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  order_row public.purchase_orders%rowtype;
  key_row public.exam_keys%rowtype;
  key_id uuid;
  key_code text;
  expiry timestamptz;
  attempt_count integer;
  valid_days integer;
begin
  select *
  into order_row
  from public.purchase_orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'PURCHASE_ORDER_NOT_FOUND';
  end if;

  if order_row.status in ('cancelled', 'refunded') then
    raise exception 'PURCHASE_ORDER_NOT_PAYABLE';
  end if;

  attempt_count := greatest((order_row.product_snapshot ->> 'attempt_count')::integer, 1);
  valid_days := nullif(order_row.product_snapshot ->> 'valid_days', '')::integer;
  expiry := case
    when valid_days is null then null
    else now() + make_interval(days => valid_days)
  end;

  select *
  into key_row
  from public.exam_keys
  where source_order_id = p_order_id
  for update;

  if not found then
    insert into public.students (id, full_name)
    select profile.id, profile.full_name
    from public.profiles profile
    where profile.id = order_row.student_id
    on conflict (id) do nothing;

    loop
      key_id := extensions.gen_random_uuid();
      key_code := 'BUY-' || upper(replace(substr(key_id::text, 1, 16), '-', ''));
      begin
        insert into public.exam_keys (
          id,
          code,
          exam_room_id,
          batch_id,
          assigned_to,
          total_attempts,
          used_attempts,
          status,
          expires_at,
          price_paid,
          payment_ref,
          is_public,
          source_order_id
        ) values (
          key_id,
          key_code,
          null,
          null,
          order_row.student_id,
          attempt_count,
          0,
          'unused',
          expiry,
          order_row.amount,
          'legacy_bank:' || coalesce(nullif(trim(p_provider_reference), ''), order_row.payment_code),
          false,
          p_order_id
        );
        exit;
      exception
        when unique_violation then
          key_id := null;
      end;
    end loop;
  else
    key_id := key_row.id;
    key_code := key_row.code;
  end if;

  update public.purchase_orders
  set status = 'fulfilled',
      provider = coalesce(provider, 'legacy_bank'),
      provider_order_ref = coalesce(
        provider_order_ref,
        nullif(trim(p_provider_reference), '')
      ),
      paid_at = coalesce(paid_at, now()),
      fulfilled_at = coalesce(fulfilled_at, now()),
      failure_code = null,
      updated_at = now()
  where id = p_order_id;

  return jsonb_build_object(
    'order_id', p_order_id,
    'status', 'fulfilled',
    'key_id', key_id,
    'key_code', key_code
  );
end;
$$;

revoke all on function private.fulfill_purchase_order(uuid, text)
  from public, anon, authenticated;

create or replace function public.create_purchase_order(
  p_product_id uuid,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  current_student_id uuid := (select auth.uid());
  product_row public.key_products%rowtype;
  existing_order public.purchase_orders%rowtype;
  order_id uuid;
  payment_code text;
begin
  if current_student_id is null
     or not exists (
       select 1
       from public.profiles profile
       where profile.id = current_student_id
         and profile.role = 'student'
     ) then
    raise exception 'NOT_AUTHENTICATED';
  end if;

  if nullif(trim(p_idempotency_key), '') is null
     or length(trim(p_idempotency_key)) > 120 then
    raise exception 'IDEMPOTENCY_KEY_INVALID';
  end if;

  select *
  into existing_order
  from public.purchase_orders
  where purchase_orders.student_id = current_student_id
    and purchase_orders.idempotency_key = trim(p_idempotency_key);

  if found then
    return jsonb_build_object(
      'order_id', existing_order.id,
      'payment_code', existing_order.payment_code,
      'amount', existing_order.amount,
      'currency', existing_order.currency,
      'status', existing_order.status,
      'expires_at', existing_order.expires_at,
      'product_snapshot', existing_order.product_snapshot
    );
  end if;

  select *
  into product_row
  from public.key_products
  where id = p_product_id
    and is_active
    and archived_at is null
  for update;

  if not found then
    raise exception 'PRODUCT_NOT_AVAILABLE';
  end if;

  order_id := extensions.gen_random_uuid();
  payment_code := 'THPT' || upper(replace(substr(order_id::text, 1, 12), '-', ''));

  insert into public.purchase_orders (
    id,
    student_id,
    product_id,
    status,
    amount,
    currency,
    product_snapshot,
    idempotency_key,
    payment_code,
    expires_at
  ) values (
    order_id,
    current_student_id,
    product_row.id,
    'pending',
    product_row.price_amount,
    product_row.currency,
    jsonb_build_object(
      'id', product_row.id,
      'code', product_row.code,
      'name', product_row.name,
      'product_kind', product_row.product_kind,
      'attempt_count', product_row.attempt_count,
      'price_amount', product_row.price_amount,
      'currency', product_row.currency,
      'valid_days', product_row.valid_days
    ),
    trim(p_idempotency_key),
    payment_code,
    now() + interval '24 hours'
  )
  on conflict (idempotency_key) do nothing;

  select *
  into existing_order
  from public.purchase_orders purchase
  where purchase.id = order_id
     or (
       purchase.student_id = current_student_id
       and purchase.idempotency_key = trim(p_idempotency_key)
     );

  if not found then
    raise exception 'PURCHASE_ORDER_CREATE_FAILED';
  end if;

  return jsonb_build_object(
    'order_id', existing_order.id,
    'payment_code', existing_order.payment_code,
    'amount', existing_order.amount,
    'currency', existing_order.currency,
    'status', existing_order.status,
    'expires_at', existing_order.expires_at,
    'product_snapshot', existing_order.product_snapshot
  );
end;
$$;

revoke all on function public.create_purchase_order(uuid, text)
  from public, anon;
grant execute on function public.create_purchase_order(uuid, text)
  to authenticated;

create or replace function public.reconcile_purchase_order(p_order_id uuid)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  order_row public.purchase_orders%rowtype;
begin
  if not private.is_admin() then
    raise exception 'ADMIN_ONLY';
  end if;

  select *
  into order_row
  from public.purchase_orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'PURCHASE_ORDER_NOT_FOUND';
  end if;

  if order_row.status = 'paid' then
    return private.fulfill_purchase_order(
      p_order_id,
      order_row.provider_order_ref
    );
  end if;

  return jsonb_build_object(
    'order_id', order_row.id,
    'status', order_row.status,
    'key_code', (
      select code from public.exam_keys where source_order_id = order_row.id
    )
  );
end;
$$;

revoke all on function public.reconcile_purchase_order(uuid)
  from public, anon;
grant execute on function public.reconcile_purchase_order(uuid)
  to authenticated;

create or replace function public.revoke_purchase_order(
  p_order_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  order_row public.purchase_orders%rowtype;
  key_row public.exam_keys%rowtype;
begin
  if not private.is_admin() then
    raise exception 'ADMIN_ONLY';
  end if;

  if nullif(trim(p_reason), '') is null then
    raise exception 'REVOCATION_REASON_REQUIRED';
  end if;

  select *
  into order_row
  from public.purchase_orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'PURCHASE_ORDER_NOT_FOUND';
  end if;

  select *
  into key_row
  from public.exam_keys
  where source_order_id = p_order_id
  for update;

  if found then
    update public.exam_keys
    set status = 'revoked',
        deleted_at = now(),
        updated_at = now()
    where id = key_row.id;
  end if;

  update public.purchase_orders
  set status = 'refunded',
      failure_code = left(trim(p_reason), 200),
      updated_at = now()
  where id = p_order_id;

  if to_regclass('public.admin_audit_log') is not null then
    insert into public.admin_audit_log (
      actor_user_id,
      action,
      entity_type,
      entity_id,
      details
    ) values (
      (select auth.uid()),
      'refund_revoke',
      'purchase_order',
      p_order_id::text,
      jsonb_build_object('reason', left(trim(p_reason), 500), 'key_id', key_row.id)
    );
  end if;

  return jsonb_build_object(
    'order_id', p_order_id,
    'status', 'refunded',
    'key_revoked', key_row.id is not null
  );
end;
$$;

revoke all on function public.revoke_purchase_order(uuid, text)
  from public, anon;
grant execute on function public.revoke_purchase_order(uuid, text)
  to authenticated;

notify pgrst, 'reload schema';
